language: cpp
branches:
  only:
    - master
    - add-ci-release
addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/libpsvr-linux64.tar.gz
    debug: true
before_install:
  - sudo apt-get update && sudo apt-get install libudev-dev
  - cd $TRAVIS_BUILD_DIR
  - ./clean.sh && ./generate.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - ./build.sh
after_success:
  - cd $TRAVIS_BUILD_DIR
  - tar -czvf libpsvr-linux64.tar.gz build/Linux64 include
