language: cpp
branches:
  only:
    - master
    - add-ci-release
addons:
  apt:
    packages: cmake
before_install:
  - sudo apt-get update && sudo apt-get install libudev-dev
script:
  - cd $TRAVIS_BUILD_DIR
  - ./build.sh
