version: '{build}'
branches:
  only:
  - add-ci-release
clone_folder: c:\projects\libpsvr
image:
  - Visual Studio 2017
  - Ubuntu
configuration:
  - Release
  - Debug
platform:
  - x64
environment:
  matrix:
  - arch: Win64
  - arch: Linux64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true
  
# skip unsupported combinations
init:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - echo %generator%

before_build:
    - cmd: |-
        cmake --version
        clean.bat
        generate.bat
    - sh: |-
        cmake --version
        clean.sh
        generate.sh

build_script:
    - cmd: c:\projects\libpsvr\build.bat
    - sh: build.sh

#Zip libpsvr.lib
after_build:
    -cmd: 7z a .\build\Win64\libpsvr\libpsvr.zip .\build\Win64\libpsvr\libpsvr.lib -r .\include\*

# Upload zip artifact
artifacts: #
    - path: .\build\Win64\libpsvr\libpsvr.zip
      name: libpsvr
      type: zip
    
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - build.bat
    - src/
