version: '{build}'
branches:
  only:
  - add-ci-release
clone_folder: c:\projects\libpsvr
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true
  
# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

install: 
  git submodule update --init

before_build:
- cmd: |-
    choco install make
    make --version
    # clean.bat
    # generate.bat

build_script:
  # c:\projects\OpenPSVR\build.bat

after_build:
  # ps: $root = Resolve-Path .\build\Win64\openpsvr; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - build.bat
    - clean.bat
    - generate.bat
    - src/
